services:
  redis:
    image: redis:7.2.1
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD?Variable not set}
    restart: unless-stopped
    # Set credentials & logging
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on >$REDIS_PASSWORD ~* +@all" > /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    volumes:
      - redisdata:/var/lib/redis/data
    ports:
      - "6375:6379"
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5435:5432"
  bot:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    command: /bin/bash -c "source venv/bin/activate && make migrate && python -m src.bot"
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  scheduler:
    build:
      context: .
      dockerfile: buildfiles/Scheduler.Dockerfile
    env_file:
      - .env
    restart: always
    command: /bin/bash -c "source venv/bin/activate && arq src.scheduler.main.WorkerSettings"
    depends_on:
      - redis

volumes:
  pgdata:
  redisdata:
