"""empty message

Revision ID: ede3fd924a83
Revises: 469afbf45230
Create Date: 2024-01-18 23:07:20.787098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede3fd924a83'
down_revision: Union[str, None] = '469afbf45230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_secret', sa.String(), nullable=True))
    op.drop_column('users', 'secret_otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret_otp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'otp_secret')
    # ### end Alembic commands ###
