"""empty message

Revision ID: 8e8031a6978e
Revises: ede3fd924a83
Create Date: 2024-01-26 14:54:45.801454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8031a6978e'
down_revision: Union[str, None] = 'ede3fd924a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwords', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('passwords_owner_id_fkey', 'passwords', type_='foreignkey')
    op.create_foreign_key(None, 'passwords', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.drop_column('passwords', 'owner_id')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('passwords', sa.Column('owner_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'passwords', type_='foreignkey')
    op.create_foreign_key('passwords_owner_id_fkey', 'passwords', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('passwords', 'user_id')
    # ### end Alembic commands ###
