"""empty message

Revision ID: f396e21d9725
Revises: 86de5fa30ee6
Create Date: 2024-01-18 22:31:21.278850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f396e21d9725'
down_revision: Union[str, None] = '86de5fa30ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.add_column('passwords', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passwords', 'comment')
    op.create_table('comments',
    sa.Column('password_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['password_id'], ['passwords.id'], name='comments_password_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('password_id', name='comments_pkey')
    )
    # ### end Alembic commands ###
