"""empty message

Revision ID: 86de5fa30ee6
Revises: 0f41b04f4827
Create Date: 2024-01-16 17:43:00.327319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86de5fa30ee6'
down_revision: Union[str, None] = '0f41b04f4827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret_otp', sa.String(), nullable=True))
    op.drop_column('users', 'hashed_master')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_master', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'secret_otp')
    # ### end Alembic commands ###
