"""delete not null constraint for records.url

Revision ID: b67054387a3b
Revises: a0455d9e7248
Create Date: 2023-11-03 00:55:25.906274

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b67054387a3b'
down_revision: Union[str, None] = 'a0455d9e7248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'url',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=True)
    # op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('records', 'url',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=False)
    # ### end Alembic commands ###
