"""recode in sqlalchemy2 style

Revision ID: be9c32772830
Revises: e451cde8c2b1
Create Date: 2023-10-23 22:54:36.149224

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be9c32772830'
down_revision: Union[str, None] = 'e451cde8c2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'text',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=True)
    op.alter_column('users', 'last_name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('users', 'language_code',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('users', 'username',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # op.create_unique_constraint('users_username_key', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('users_username_key', 'users', type_='unique')
    op.alter_column('users', 'username',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('users', 'language_code',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('users', 'last_name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('comments', 'text',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=False)
    # ### end Alembic commands ###
