"""fix users.username

Revision ID: f4b3abdd6ac3
Revises: be9c32772830
Create Date: 2023-10-23 23:01:19.929719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b3abdd6ac3'
down_revision: Union[str, None] = 'be9c32772830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('users_username_key', 'users', ['username'])
    # ### end Alembic commands ###
